"""

# Training is handled by IFTrainWorker in gui.py — this script is kept for reference

train_if.py
===========
Trains an Isolation Forest anomaly detector on synthetic process scan data.

Pipeline
--------
1. Load synthetic CSV (generated by synth_gen.py)
2. Drop constant / meta columns
3. Impute missing values (-1 sentinel)  [entropy cols are 56% missing in normal data]
4. Scale features with StandardScaler   [critical: IF is distance-based and biases
                                          toward large-magnitude features without scaling]
5. Fit IsolationForest
6. Save model + scaler + feature list   [all three needed at inference time]

Usage
-----
    python train_if.py --data synthetic_data.csv --out models/

Outputs
-------
    models/if_model.pkl    — trained IsolationForest
    models/if_scaler.pkl   — fitted StandardScaler  (apply before scoring)
    models/if_features.json — ordered feature list  (columns the model expects)

Inference (in your scanner)
---------------------------
    import joblib, json, numpy as np

    scaler   = joblib.load("models/if_scaler.pkl")
    model    = joblib.load("models/if_model.pkl")
    features = json.load(open("models/if_features.json"))

    # Build a feature vector from a scan (must match feature order exactly)
    row = {col: value_or_imputed for col in features}
    X   = np.array([[row[f] for f in features]])
    X_s = scaler.transform(X)
    score = model.score_samples(X_s)[0]   # more negative = more anomalous
    pred  = model.predict(X_s)[0]          # -1 = anomaly, 1 = normal
"""

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------

import argparse
import json
import os
import sys

import numpy as np
import pandas as pd

import joblib

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# same replacement across the entire pipeline

MISSING = -1

# missing value imputation strategy per column group
# entropy_mean and entropy_max are -1 MISSING for ~57% of normal rows because most processes have no private executable regions to measure entropy on
# so it imputes with 0.0: meaning no entropy was observed which is distinct from a low but present entropy value and preserves the  signal

# it's replaced with 0.0 which means the entropy was not observed and it doesn't confuse the IF as -1 would be counted as a legit data point which is not possible for entropy values

IMPUTE_ENTROPY_COLS = {"entropy_mean", "entropy_max"}
IMPUTE_ENTROPY_VALUE = 0.0

# all other missing values: impute with 0 which is safe for count and perf features

# imputation: process of replacing missing data with 0.0 to not confuse IF

IMPUTE_DEFAULT_VALUE = 0.0

# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

# THIS WAY OF TRAINING IS ONLY DONE THROUGH COMMAND LINE
# THEREFORE THIS MODULE IS NOT DIRECTLY USED IN THE PROGRAM
# ALL OF THE TRAINING IS DONE BY WORKERS IN GUI

# progress_cb and log_cb are optional callbacks used by IFTrainWorker in gui.py
# when called from the GUI, progress_cb emits to the progress bar and log_cb emits to the console
# when called from the command line, both are None and print() is used instead
# returns (model_path, scaler_path, feature_path) so the GUI can load the model automatically

def train(

    csv_path: str,
    out_dir: str,
    contamination: float = 0.02, # expected anomaly fraction (matches anomaly_rate)
    n_estimators: int = 200, # more trees = more stable scores
    random_state: int = 42,
    progress_cb = None, # optional: callable(int) 0-100, used by GUI progress bar
    log_cb = None,      # optional: callable(str), used by GUI console

    ) -> tuple:

    def _progress(pct: int):
        if progress_cb:
            progress_cb(pct)

    def _log(msg: str):
        if log_cb:
            log_cb(msg)
        else:
            print(msg)

    os.makedirs(out_dir, exist_ok = True)

    # ---- 1. Load data (0-10%) ----------------------------------------

    _log(f"[IF] Loading data from {csv_path} ...")
    _progress(5)

    df = pd.read_csv(csv_path)

    _log(f"[IF] Loaded {len(df)} rows x {len(df.columns)} columns")

    # ---- 2. Clean (10-20%) -------------------------------------------
    _progress(10)

    # drop meta columns (meta_timestamp, meta_process_name etc)
    # drop non-meta columns where std == 0 EXCLUDING -1 sentinel values from the std check
    # this is critical: including -1 in the std check would give false variance to columns
    # that are actually constant in real data — so we filter them out first

    meta   = [c for c in df.columns if c.startswith("meta_")]
    always = [c for c in df.columns
              if not c.startswith("meta_") and
              df[c][df[c] != MISSING].std() == 0]

    drop = list(set(meta + always) & set(df.columns))

    if drop:
        df = df.drop(columns = drop)
        _log(f"[IF] Dropped {len(drop)} column(s): {drop}")

    # impute -1 sentinel with 0.0
    # entropy absence = 0.0; counts absence = 0
    # flat 0.0 for everything — keeps imputation consistent and simple

    for col in df.columns:
        mask = df[col] == MISSING
        if mask.any():
            df.loc[mask, col] = 0.0

    assert not (df == MISSING).any().any(), "Imputation missed -1 sentinel"

    features = list(df.columns)

    _log(f"[IF] Training on {len(features)} features")
    _progress(20)

    # ---- 3. Scale (20-30%) -------------------------------------------

    # convert dataframe into raw numpy array of 64 bit floats
    # this format is required for sklearn training

    X = df.values.astype(float)

    # scale: CRITICAL for IF
    # without scaling, features with large ranges (io_write_kb) dominate the split selection making smaller features invisible
    # StandardScaler centres each feature to mean = 0 std = 1

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    _log("[IF] StandardScaler fitted")
    _progress(30)

    # ---- 4. Train with warm_start (30-90%) ---------------------------

    # uses warm_start to add trees in small batches
    # this allows the GUI progress bar to update smoothly rather than freezing until done

    _log(f"[IF] Training IsolationForest  (trees={n_estimators}, contamination={contamination}) ...")

    BATCH_SIZE = 10

    model = IsolationForest(
        n_estimators  = BATCH_SIZE,
        contamination = contamination,
        warm_start    = True,
        random_state  = random_state,
        n_jobs        = -1,
    )

    model.fit(X_scaled)
    trained = BATCH_SIZE

    while trained < n_estimators:
        batch = min(BATCH_SIZE, n_estimators - trained)
        model.n_estimators += batch
        model.fit(X_scaled)
        trained += batch
        pct = 30 + int(trained / n_estimators * 60)
        _progress(min(pct, 90))

    # ---- 5. Validate (90-95%) ----------------------------------------

    # run the model on its own training data to check contamination
    # if it was set to 2% by default but returned 50%, then something is messed up

    preds   = model.predict(X_scaled)
    flagged = (preds == -1).sum()

    _log(
        f"[IF] Training complete. "
        f"Flagged {flagged}/{len(preds)} rows as anomalies "
        f"({flagged/len(preds)*100:.1f}%)  "
        f"[expected ~{contamination*100:.0f}%]"
    )
    _progress(95)

    # ---- 6. Save (95-100%) -------------------------------------------

    # save artefacts
    # all files from training saved
    # all are required to score a live process

    model_path   = os.path.join(out_dir, "if_model.pkl")
    scaler_path  = os.path.join(out_dir, "if_scaler.pkl")
    feature_path = os.path.join(out_dir, "if_features.json")

    joblib.dump(model,  model_path)
    joblib.dump(scaler, scaler_path)

    with open(feature_path, "w") as fh:
        json.dump(features, fh, indent = 2)

    _log(f"[IF] Saved model    -> {model_path}")
    _log(f"[IF] Saved scaler   -> {scaler_path}")
    _log(f"[IF] Saved features -> {feature_path}")
    _progress(100)

    # return the three file paths so the GUI can load the model automatically after training
    return model_path, scaler_path, feature_path

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

# simple entry point for the command line version
# THIS IS NOT USED WHEN USING GUI VERSION

def main():

    parser = argparse.ArgumentParser(

        description = "Train Isolation Forest on synthetic process scan data."
    )

    parser.add_argument("--data", required = True,  help = "Path to synthetic_data.csv")

    parser.add_argument("--out", default = "models", help = "Output directory")

    parser.add_argument("--contamination", type = float, default = 0.02, help = "Expected anomaly fraction (default 0.02 = 2%%)")

    parser.add_argument("--trees", type = int, default = 200, help = "Number of trees (default 200)")

    parser.add_argument("--seed", type = int, default = 42)

    args = parser.parse_args()

    train(

        csv_path      = args.data,
        out_dir       = args.out,
        contamination = args.contamination,
        n_estimators  = args.trees,
        random_state  = args.seed,
    )

if __name__ == "__main__":
    main()